### ISSUE TITLE
log robot position (netbook)

### ISSUE THREAD

**Issue by fsaintma** [iot-lab/iot-lab#113]
OML  with x,y,z theta
file csv

<id exp>/mobility/m3-<id>.oml

protocol: 4
domain: 7458
start-time: 1401280300
sender-id: m3-9
app-name: control_node_measures
schema: 0 _experiment_metadata subject:string key:string value:string 
schema: 1 control_node_measures_consumption timestamp_s:uint32 timestamp_us:uint32 power:double voltage:double current:double 
content: text

1.941124	1	1	1401280301	34666	0.141313	3.250000	0.043466
1.941948	1	2	1401280301	99027	0.141313	3.250000	0.043471
1.942192	1	3	1401280301	163389	0.141313	3.250000	0.043491
1.942375	1	4	1401280301	227750	0.141435	3.248750	0.043540

**Comment by pissard** [comment]
ok. integration in the tutorial.
 https://www.iot-lab.info/tutorials/submit-an-experiment-with-a-mobile-m3-nodes-using-the-web-portal/
