### ISSUE TITLE
Support "+" style email addresses upon registration

### ISSUE THREAD

**Issue by fambon** [iot-lab/iot-lab#134]
Some users provide "+" style email addresses upon registration, e.g. first.last@mail.org+TOPIC, typically for filtering purposes.  While this type of addresses is supported by postfix, using them causes the iot-lab registration process to fail silently.
- [ ] make registration failure explicit to the user
- [ ] possibly support "+" style emails

**Comment by vandaele** [comment]
Will not be implemented.
