### ISSUE TITLE
Robot unstable after long uptime

### ISSUE THREAD

**Issue by fsaintma** [iot-lab/iot-lab#179]
We encounter problem with execution of robot circuit if the robot is switch on during a long time.

**Comment by fsaintma** [comment]
First correction : add crontab for restarting ROS each night and verify behaviour of the robot

**Comment by pissard** [comment]
the bug is not solve but we have observed that:
* start/stop ROS does not solve the problem
* on/off the robot does not solve the problem
* halt the PC solve the problem

**Comment by schrein** [comment]
The problem was occurring a version of netbook with ROS Indigo / Ubuntu 14.04 LTS. It has been fixed with ROS Kinetic / Ubuntu 16.04 LTS.
