### ISSUE TITLE
Add support to start/stop the open node debugger on M3 nodes.

### ISSUE THREAD

**Issue by cladmi** [iot-lab/iot-lab#180]

**Comment by cladmi** [comment]
Release on Grenoble dev platform

**Comment by fsaintma** [comment]
* Add tutorial page : https://www.iot-lab.info/?page_id=4377&preview=true
* You can reset/halt and flash firmware with gdb but it's impossible to add breakpoints.
* You must desactivate in openlab/platform/platform.c line 81 the sleep mode and recompile your firmware (https://groups.google.com/forum/#!topic/osdeve_mirror_rtos_ecos-discuss/_vmWTGdr1O8)
   // Enter SLEEP mode
  //asm volatile("wfi");
* Now when you debug tutorial_m3 firmware you have problem with event timer

**Comment by cladmi** [comment]
You managed to add breakpoints in the tutorial but I couldn't do it, I got the following error:

```
(gdb) c
Continuing.
Warning:
Cannot insert hardware breakpoint 1.
Could not insert hardware breakpoints:
You may have requested too many hardware breakpoints/watchpoints.
```

I didn't deactivated the `asm volatile("wfi") however, maybe it comes from here.
