### ISSUE TITLE
Upgrade Robot to ROS Indigo

### ISSUE THREAD

**Issue by schrein** [iot-lab/iot-lab#190]
Upgrade robot netbook to Ubuntu 14.04 LTS and ROS Indigo.

**Comment by RayBor** [comment]
We have a new intern in Lille whose job is exactly this. He's currently discovering the whole system but maybe you should see with him ?

**Comment by pissard** [comment]
two main aspects to watch:
  * The default 3D sensor is now Asus Xtion Pro. 
  * Environment Variables to configure your turtlebot 
see : http://wiki.ros.org/Robots/TurtleBot/indigo/Migration
