### ISSUE TITLE
3D map: Show node as tooltip on mouse-over

### ISSUE THREAD

**Issue by miri64** [iot-lab/iot-lab#193]
It took me a while to realize that the node-IDs are shown below the 3D map when I had the mouse over a node. Maybe showing it in a tool tip or a similar thing would be more intuitive.

**Comment by aabadie** [comment]
The 3D Map was reworked a bit in latest version of the testbed-webportal. The node id is now displayed as a tooltip on the top right corner when hovering a node.

I close this issue but feel free to reopen it of you disagree.
