### ISSUE TITLE
Prompt error when asking to 'Reset password' on a non activated account.

### ISSUE THREAD

**Issue by cladmi** [iot-lab/iot-lab#194]
Currently, it's possible to do a 'reset password' procedure with a non activated account.
This should show an error message or tell the error in the email.

**Comment by aabadie** [comment]
This is fixed in the new version of the testbed-webportal: it's not possible to list deactivated accounts, thus not possible to reset the password of a deactivated account.

Closing this but feel free to reopen if you disagree.
