### ISSUE TITLE
REST server breaking when testing `experiment-cli wait` error cases

### ISSUE THREAD

**Issue by cladmi** [iot-lab/iot-lab#198]
I wanted to try to find the `experiment-cli wait` server error to handle them locally.
I launched ~20 experiment-cli wait to see the possible errors

After some time I get this error on some execution

```
$ experiment-cli wait
Waiting that experiment 26056 gets in state Running
HTTP Error 500: 
	Too many open files
```

And then on all other and every time I run a REST request I get:

```
 experiment-cli wait
HTTP Error 401: Unauthorized: Wrong login/password

	Register your login:password using `auth-cli`
```

Website is affected also

![unauthorized_rest](https://cloud.githubusercontent.com/assets/241401/8872456/6c76fa5c-31fd-11e5-9893-f99f4838234d.png)

It fixes itself after some time.

It looks like not correctly closed files gets garbage collected after a "long" time, or java taking it's time to really close the open files.

**Comment by cladmi** [comment]
I previously already had issue after a long time use of only one 'experiment-cli wait' but it took longer.
By default it does requests with 5 seconds between each.

**Comment by fsaintma** [comment]
Fix on dev platform and refactoring code. The bug is due to bad disconnect ldap connexions.
