### ISSUE TITLE
How do I monitorate the packet delivery using OpenWSN?

### ISSUE THREAD

**Issue by brunoliveira8** [iot-lab/iot-lab#199]
Hi all,
I am trying to run an experiment using OpenWSN. I need to see the network traffic, however, i cant create the tun interface on IoT-Lab because I am not root user.

So, I tunneled the root mote connection to my PC, and ran the openvisualizer. When I used Wireshark to monitorate the tun interface just RPL packets could be visualizated. Moreover, I am not able to ping or use a COAP request.

Does someone have the same issue?

**Comment by cladmi** [comment]
I will answer on the users mailing list, it will have more visibility and other users knowing the answer.

**Comment by brunoliveira8** [comment]
I really appreciate your help.

Regards.
