### ISSUE TITLE
Add options to allow selecting values out of the resulting json

### ISSUE THREAD

**Issue by cladmi** [iot-lab/iot-lab#200]
Selecting values out of cli-tools output in a shell is not adapted. I mainly rely on `grep`, `sed` which non optimized for the structured output.

Adding a selection à la XPATH (see which one to use) can simplify this task.

**Comment by cladmi** [comment]
Ideas https://github.com/iot-lab/cli-tools/tree/jmespath

**Comment by aabadie** [comment]
jmespath is ntegrated in the cli-tools. Closing this.
