### ISSUE TITLE
Contiki 3.0

### ISSUE THREAD

**Issue by brunoliveira8** [iot-lab/iot-lab#201]
Hello,

Do you have any idea when the wsn430's platform will be implemented to Contiki 3.0?

Thank you for your time.

Regards,

**Comment by jerem0808** [comment]
Indeed, it would be nice to have it. Or does it exist somewhere else ? 
Thank you in advance

**Comment by cladmi** [comment]
Hi, there is ongoing work to make it work with m3 and a8-m3 nodes on the ustream-3-x branch.

> https://github.com/iot-lab/contiki/tree/upstream-3-x

However we don't have time to do it for wsn430, but you may want to take a look yourself if interested.

**Comment by jerem0808** [comment]
Thank you for your response
