### ISSUE TITLE
Lille Test-Bed: Lost home directory

### ISSUE THREAD

**Issue by jpope8** [iot-lab/iot-lab#209]
I had a home directory and files on the Lille test bed as of two days ago - but when I tried to login today I got the message below - any help/resolution greatly appreciated.  I still have my home directory on the Rennes test bed.

$ ssh pope@lille.iot-lab.info
Linux lille 2.6.32-5-amd64 #1 SMP Mon Feb 29 00:33:51 UTC 2016 x86_64
Welcome FIT IoT-LAB users

Charter:
* FIT IoT-LAB is shared among several users, so make reasonable use of the platform
* Quote FIT IoT-LAB in your scientific papers

Post your issues on:
* the user mailing-list: users@iot-lab.info
* or the bug-tracker: https://github.com/iot-lab/iot-lab/issues
Last login: Thu Apr 14 00:49:47 2016 from byod-natout-129-174-182-2.byod.gmu.edu
**Could not chdir to home directory /senslab/users/pope: No such file or directory**
pope@lille:/$ pwd
/
pope@lille:/$ exit

**Comment by cladmi** [comment]
Hi, it's an issue with the nfs mounted user directory. I rebooted the server and it's now up and running.
Thank you for reporting.

```
Last login: Thu Apr 14 16:52:42 2016 from
harter@lille:~$ pwd
/senslab/users/harter
harter@lille:~$ 
```

For issues like this it's better to post them on the mailing list as they are not code related and so all users might see it.
