### ISSUE TITLE
A8 Node Energy Model

### ISSUE THREAD

**Issue by nidiascampos** [iot-lab/iot-lab#216]
Hi,
How can I measure energy in A8 node?
Does someone know if there is an energy model or tool?
So I could measure the energy wasted by my apps on A8 node.

Thanks in advance.

**Comment by aabadie** [comment]
You can create an experiment with a monitoring profile for A8 nodes. Just adapt [the tutorial](https://www.iot-lab.info/tutorials/monitoring-consumption-m3) for monitoring power consumption of M3 nodes.

I'm closing this for now but feel free to reopen if you still have problems.
