### ISSUE TITLE
I can not connect to the IoT lab SSH servers

### ISSUE THREAD

**Issue by anonyette** [iot-lab/iot-lab#218]
I am a new user to the IoT platform and i have been trying to connect to the IoT lab SSH servers. I followed the instructions for the ssh key pair generation  and made sure that there are no spaces while copying it to my profile, however, even after many many attempts it still gives me the access denied (public key) error. Can you please advice?

**Comment by schrein** [comment]
Please run carefully https://www.iot-lab.info/tutorials/ssh-access/
