### ISSUE TITLE
tunslip dissconectiov

### ISSUE THREAD

**Issue by nahlaiot** [iot-lab/iot-lab#219]
tunslip6: can't connect to ``localhost:2000'': Connection refused

**Comment by nahlaiot** [comment]
some time it works and sometime not why???????????

**Comment by schrein** [comment]
If you are using tunslip on the IoT-LAB frontend server, you shoud be aware about:

- the TCP port used by tunslip is 20000 and not 2000
- you can only open one socket to a given node, be sure you do not open in another terminal a netcat or a serial_aggregator

Could you try again please ? If you experience again troubles, you can reopen the issue.
