### ISSUE TITLE
Running script on SSH frontend

### ISSUE THREAD

**Issue by MuyuXiaoxiang** [iot-lab/iot-lab#222]
Hello Sir,
            I am so sorry to bother you. Recently,I want to store the temperature data on my computer. So I run script on SSH frontend. I follow the tutorials to run my experiment. What's more, the script is provided by you and I associate the aggregator_script with the nodes by the code(`<login>@grenoble:~$ iotlab-experiment submit -d 60 -l 5,archi=m3:at86rf231+site=grenoble,sensors-collecting.iotlab-m3 --site-association grenoble,script=aggregator_script`).  But when I run the experiment following the tutorial which is [Running script on SSH frontend](https://www.iot-lab.info/tutorials/iotlab-runscript-client/ ), it will tell me some problem. If I run the code `screen -ls`, it tells me 'No Sockets found in /var/run/screen/S-zhfan.'.
When I run the code ` iotlab-experiment script --status`, it shows '{
    "0": {
        "grenoble.iot-lab.info": "Idle"
    }
}
'
      I have searched  some methods,but I cannot solve it.Could you help me?Thank you!
      Zhfan.

**Comment by rienafairefr** [comment]
I retried running the tutorial without any issues.
For SSH running script in the background for experiments, you have a debug log in `~/.iot-lab/last/run_script.log`, this would tell you more about the run_script, if it started, if it failed, etc.
