### ISSUE TITLE
testbed-beta: can't update user profile

### ISSUE THREAD

**Issue by miri64** [iot-lab/iot-lab#223]
When trying the new web-frontend I always get the following modal:

![](https://user-images.githubusercontent.com/675644/41278606-817af824-6e2a-11e8-8289-08cd2d1f3e90.png)

But when I actually try to update my user category, I get an error and the profile isn't updated

![](https://user-images.githubusercontent.com/675644/41278663-a8661c3e-6e2a-11e8-9e8e-4a84fba0477e.png)

**Comment by rienafairefr** [comment]
Thanks for the feedback @miri64, it seems your email doesn't match our expected format for an email address, this should be fixed soon :+1:

**Comment by rienafairefr** [comment]
@miri64 we modified the code on our side, your email should pass the validation this time, can  you confirm it's working for you now ?

**Comment by miri64** [comment]
Yes, it works now!

**Comment by rienafairefr** [comment]
Thanks for your help Martine, closing this :-)
