### ISSUE TITLE
Adding an association to an A8 node

### ISSUE THREAD

**Issue by druzmieres** [iot-lab/iot-lab#224]
I'm getting an error message when choosing A8 nodes and trying to add an association to a profile. Actually, it happens with M3 nodes too if I don't select a firmware, and as far as I know there's no firmware for A8 nodes.

![imagen](https://user-images.githubusercontent.com/11931391/41744230-29481652-7571-11e8-904e-0fb29c6d73b7.png)

**Comment by bformet** [comment]
Fixed. Thanks for reporting
