### ISSUE TITLE
Using a PC as client/server instead of a node

### ISSUE THREAD

**Issue by druzmieres** [iot-lab/iot-lab#227]
I've been running experiments on the platform, measuring CPU and Memory
usage on A8 nodes using the HTTP/2 protocol. For this I've using an A8
node as the client and another one as the server. Now, I'd like to run
similar experiments, but this time I want to use an A8 node as the client
and a computer as the server and vice versa. Is it possible to do this?

**Comment by schrein** [comment]
Hello @druzmieres, A8 nodes use IPv4 private address  (behind NAT) and IPv6 public address. If you initiate trafic from the A8 nodes, you can reach any HTTP server on Internet. If you initiate trafic from remote server, the easiest way is to use IPv6. See https://www.iot-lab.info/tutorials/understand-ipv6-subnetting-on-the-fit-iot-lab-testbed/ for more info.
