### ISSUE TITLE
Cannot compile RIOT OS in IoTLab

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#231]
Hello, I am not able to compile RIOT OS in IoTLab. Compiling Contiki OS is not an issue though.

![image](https://user-images.githubusercontent.com/25517038/45201498-3feb4d00-b23b-11e8-92e9-9d6e7f9feeb5.png)

**Comment by aabadie** [comment]
As a side note, you might need a recent version of arm-none-eabi-gcc (7.3) to build RIOT.
See the [wiki](https://github.com/iot-lab/iot-lab/wiki/Versions-of-the-GNU-toolchain-for-ARM) that explains how to make this version the default on the SSH frontend.

**Comment by npcode15** [comment]
Thank you.
