### ISSUE TITLE
Differentiate Nodes from c file

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#238]
Hello, is there a way to differentiate between nodes from c file.

Consider a scenario where I have 2 M3 nodes. In main.c file, I would like to add an if-else condition to differentiate between 2 nodes. Assuming one as the sender and the other as the receiver, is there a way to do this.

The only way I can think of is using, IP address. But, I would like to know if there is a better way?

Thanks.

**Comment by rienafairefr** [comment]
You can build two firmwares, with the values incorporated in the C code with a `#define` (passed to the compiler), depending on your build system it relatively easy to do , and then flash them independently in your experiment submission. 

Another possibility is using the unique identification code (UID) that is inside the microcontroller, for inspiration/ideas you can go into the iot-lab/openlab repo (look at the appli/iotlab/lib/scripts/generate_uid_dict.py)

**Comment by npcode15** [comment]
@rienafairefr 
Thanks.
