### ISSUE TITLE
Connection to nodes refused

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#240]
Hello, I am having trouble connecting with m3-nodes.

Exp ID: 134594, 134450

![image](https://user-images.githubusercontent.com/25517038/45716775-8f941780-bb5d-11e8-824a-48c290540480.png)

Even, aggregator is not working.
![image](https://user-images.githubusercontent.com/25517038/45717067-6b850600-bb5e-11e8-8d13-16239adf90e3.png)

Basically, Exp 134594 is a reload from 134409 which was working just fine. I was able to access nodes without any issue.

Thanks.

**Comment by npcode15** [comment]
This is issue is still troubling me.
![image](https://user-images.githubusercontent.com/25517038/46012520-29445300-c08f-11e8-970a-79dab6c5ddac.png)

Experiment IDs - 135198 and 135200

Please help ASAP. Thanks

**Comment by rienafairefr** [comment]
Sometimes you get this error because two processes try to connect to a node at the same time, is that something you are doing ? You can't have two serial aggregators, or a serial aggregator+ a netcat.

**Comment by npcode15** [comment]
@rienafairefr Yes, I had a netcat and aggregator opened at this instance. But, it does deny connections without having multiple connections opened as well. But, thanks.

**Comment by schrein** [comment]
We identify an issue with this problem. It should be fix now.

**Comment by rienafairefr** [comment]
Hi @npcode15, there was an issue on the testbed due to SSH servers getting too many connections, it should be fixed now, don't hesitate to re-open a new one if you still get an error
