### ISSUE TITLE
Deployment error at Strasbourg

### ISSUE THREAD

**Issue by smnblt** [iot-lab/iot-lab#241]
Hello community, I'm a registered user with "bolettie" username. Since yesterday (2019-9-19) i'm having issues while launching experiments on Strasbourg site. Each experiment (new o relaunched) results in "deployment error". Furthermore the A8 shared folder results to be not accessible. 
Something similar happened some days ago. 
I'm wondering if this is a problem regarding iot-lab connectivy issues or concerning my personal account.
Hoping for a soon feedback, thanks in advance.
Regards

**Comment by schrein** [comment]
Hi,

yes indeed there was a problem since yesterday with our NFS fileserver which ran out of memory (oom-killer). That's why you couldn't launch A8 experiment because those nodes mount remote file systems on the fly. 

I've restart the NFS server, it's working again.

Best,
Guillaume
