### ISSUE TITLE
Code execution difference | IoTLab vs Native

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#243]
Hello, I flashed 2 firmware in the experiment 135558.

Firmware Link - https://github.com/npcode15/RIOTOS_PingPong_Exp/tree/master/Firmware%20-%20IoTLab
Repository Name - RIOTOS_PingPong_Exp

In the repository, in snd_pkt_udp/main.c - I have a while loop which should execute 1000 times. It works just fine in the Native execution whereas the execution fails to replicate the same results in the IoTlab environment. The _cnt_ variable is somehow not incrementing and causing incorrect execution. Serial aggregator is only able to capture the loop result twice no matter what.

Please look at the highlighted content in the log (in the screenshots below):
**IotLab:** 
![image](https://user-images.githubusercontent.com/25517038/46196981-1b304580-c2ce-11e8-800d-44c21a558220.png)

**Native:** 
![image](https://user-images.githubusercontent.com/25517038/46196868-c12f8000-c2cd-11e8-9da2-6450b1b9e28d.png)

Clearly, the _cnt_ variable did not increment in IotLab but it did in the Native execution. It seems like a weird issue but please help me solve. 

Thank you.

**Comment by rienafairefr** [comment]
in the C code  snd_pkt_udp/main.c it's not clear that cnt should increment, let alone increment 1000 times, 
```
static int send_data = 1;

int main(void)
{
int cnt = 0
while (cnt<9)
{
    if (send_data == 1000){
        cnt = cnt +1;
    }
}
}
```
I might be missing something, where is send_data mutated ?

**Comment by npcode15** [comment]
Sorry, I update the wrong value. I ran with a smaller value of 9 earlier, did not work. then tried with 1000 did not work.

**Comment by fambon** [comment]
@rienafairefr if I am not mistaken, cnt will get incremented 9 times (once every time send_data == 1000)

**Comment by npcode15** [comment]
@fambon @rienafairefr  
No, 'cnt' will increment thousand times everytime send_data == 1. That code was a silly mistake. I corrected the mistake.
![image](https://user-images.githubusercontent.com/25517038/46232203-04243e80-c334-11e8-802f-6999ab5f5e5a.png)

The problem is even the faulty code was to run, there should have been an infinite while loop. whereas the code faulty/correct only runs twice. 

**I hope this is not confusing**
Something happens and it gets stuck in the loop itself. It never exits because if loop was to exit, there is a log statement right after the loop, which never gets executed.

**Comment by npcode15** [comment]
Found a weird solution. Apparently, adding a print statement to the while loop did the trick. I have no explanation yet, why this worked but, I will update the comment if I find any. 

I am closing the issue. Thanks.
