### ISSUE TITLE
fibroute command not found

### ISSUE THREAD

**Issue by teaserrahul** [iot-lab/iot-lab#247]
![screenshot 2018-10-14 22 03 26](https://user-images.githubusercontent.com/26592576/46919459-600de900-cffd-11e8-8d14-1ebc2253499a.png)
I am performing the experiment as described in [https://www.iot-lab.info/tutorials/riot-rpl-m3/](url). I got an error for the fibroute command. How to resolve this error, please help!

Thanks

**Comment by carlotapares** [comment]
Check this out [https://github.com/RIOT-OS/RIOT/issues/8783](url)

**Comment by aabadie** [comment]
Int RIOT shell, the `fibroute` command was replaced by the `nib route` command. The tutorial was updated according to this.
