### ISSUE TITLE
WSN430 Compilation

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#248]
Hello, 

I would like to compile for the WSN430 in RIOT and Contiki. I am not able to find the board/platform ID for the same. RIOT only has configuration files for m3 and a8 in (boards)

![image](https://user-images.githubusercontent.com/25517038/47165654-0a1c9800-d2c0-11e8-8d5c-463c7ee75fec.png)

Even though both RIOT and Contiki supports WSN430.
![image](https://user-images.githubusercontent.com/25517038/47165731-3f28ea80-d2c0-11e8-8cab-52249f4db000.png)

Please let me know how can I do this. Thank you.

Thank you.

**Comment by aabadie** [comment]
In RIOT, you have 2 wsn430 based boards:
```
$ ls boards/ | grep wsn430
wsn430-v1_3b
wsn430-v1_4
```

**Comment by npcode15** [comment]
Yes, I am aware of that. But, since there was no "iotlab" prefix I assumed it was probably missing. But, Thank you.

**Comment by npcode15** [comment]
Hello,

@aabadie 

```
@strasbourg:~$ nc wsn430-100 20000
@strasbourg:~$ nc wsn430-101 20000
@strasbourg:~$
```

I am not able to access the node via ```nc```

I flashed my code earlier. Later I followed the following tutorial and flashed the hex file from the tutorial
https://www.iot-lab.info/tutorials/submit-experiment-wsn430-web/

Same result (as mentioned above)

Thank you.
