### ISSUE TITLE
IP/MAC Address - IoTLab Nodes

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#250]
Hello, 

I would like to know if there is a document or a way to find the IP/MAC addresses of the individual nodes. I flash the nodes with a shell enabled build and then use the shell to find the IP and MAC addresses via command ```ifconfig```. I am not able to do the same for ```WSN430 nodes```.

The following happens when I try to execute ```ifconfig``` in the shell:
![image](https://user-images.githubusercontent.com/25517038/47379477-9cf27380-d6c0-11e8-8bf9-4d997c4df9c3.png)

Please let me know what are my alternatives.

Thank you.

@aabadie @rienafairefr 
I apologize for explicit tagging but, I really need help. Thanks

**Comment by schrein** [comment]
Hello @npcode15 , please look at this page https://github.com/iot-lab/iot-lab/wiki/Get-M3-and-A8-M3-nodes-uid---ipv6-address-match , we have an unique UID per node which is used by platform OS in order to construct IP address.
