### ISSUE TITLE
Missing radio driver | M3/at86rf231 | Contiki

### ISSUE THREAD

**Issue by npcode15** [iot-lab/iot-lab#253]
Hello, I was looking radio driver file for Contiki M3.

I was not able to find anything in "contiki/dev/"

I was able to find other drivers such as "cc2420". Could someone help me locate the same.

Thank you.

**Comment by schrein** [comment]
Hi @npcode15 , the Contiki platform/iotlab-m3 use an indirection to the platform/openlab (see platform/iotlab-m3/Makefile.iotlab-m3) . Furthermore, the platform/openlab use external/generic M3 drivers from the https://github.com/iot-lab/openlab repository. If you follow setup instruction from  https://github.com/iot-lab/iot-lab/blob/master/Makefile , all dependencies should have been downloaded automatically by this Makefile.
