### ISSUE TITLE
CoAP server with public IPv6 and A8-M3 nodes (no "routers" in the help menu)

### ISSUE THREAD

**Issue by nainiayoub** [iot-lab/iot-lab#261]
On the border router shell, when I type "help" the "routers" command does not exist, any idea? I really need this to work.

**Comment by aabadie** [comment]
Thanks for reporting the issue. My guess is that you are trying the RIOT tutorial with CoAP on A8-M3.

There is indeed an error in the tutorial: the `routers` command was removed from RIOT a few releases ago. But you can get the list neighbors with the `nib neigh` command.

**Comment by aabadie** [comment]
This was already answered, closing this.
