### ISSUE TITLE
Missing features | New Experiment Portall web_portal

### ISSUE THREAD

**Issue by iotlovers** [iot-lab/iot-lab#267]
there is no action tab or bottom or any thing
i tried linux (chrome and firefix) and win 10 (cherome and win 10)
what should i do ?
i checked by diffrent systems

**Comment by rienafairefr** [comment]
Hi,
we think we've identified the bug, to get the fix you should logout-then-login and refresh (shift-F5) the page.
Do tell us if ther problem still occurs.
