### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ngpjunior** [iot-lab/iot-lab#280]
Hi,
I can not send COAP requests by CLI
---------------------------------------------------------------------------
request:
       coap get 'coap://[2001:660:4403:048a::3055]:5683/sensor/light'
error:
   Error: getaddrinfo ENOTFOUND [2001:660:4403:48a::3055]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at RetrySend.emit (events.js:198:13)
    at /usr/lib/node_modules/coap-cli/node_modules/coap/lib/retry_send.js:49:28
    at process._tickCallback (internal/process/next_tick.js:63:19)
----------------------------------------------------------------------------
The tun interface are working well.
In a nodejs script the requests are working well. But I need to do quick tests.
Can anyone help me? Thanks

**Comment by vandaele** [comment]
We had an issue with the coap-cli nodejs package installed on our new Debian Stretch servers.
We removed our dependency to nodejs and installed another CoAP client on frontend servers, e.g. [aiocoap-client](https://aiocoap.readthedocs.io/en/latest/module/aiocoap.cli.client.html)
