### ISSUE TITLE
MQTT connection

### ISSUE THREAD

**Issue by JKostov** [iot-lab/iot-lab#289]
I am trying to connect from my local PC to the MQTT broker at  [mqtt.iot-lab.info](mqtt.iot-lab.info) on 8883 port with this [certificate](https://www.iot-lab.info/assets/misc/docs/mqtt/iot-lab-ca.pem), but I'm getting `Error: Network is unreachable`.
Is the MQTT broker running on  mqtt.iot-lab.info:8883?

Also when trying to connect from the SSH frontend I get this error: `Unable to connect (Lookup error.)`

**Comment by fsaintma** [comment]
Hi @JKostov, we have just restarted the server. Should you try again please ?
Best regards

**Comment by JKostov** [comment]
Hello @fsaintma, I tried it now, and it is working. I'm closing the issue.
Thank you!
