### ISSUE TITLE
Nodes are down or unavailable but status say they work

### ISSUE THREAD

**Issue by FlapKap** [iot-lab/iot-lab#312]
During my usage of IoT-LAB i've encountered some nodes that consequently errors out when pushing firmware to them. They are

- st-lrwan1-10.saclay.iot-lab.info
- samr34-1.grenoble.iot-lab.info
- samr34-2.grenoble.iot-lab.info

at the saclay and grenoble site

**Comment by evvvsss** [comment]
+ I have the same issue: nodes nrf52dk (Saclay) do not work (fail during flashing firmware)

**Comment by FlapKap** [comment]
In addition to this, the st-lrwan1 nodes seems to be quite flaky at the moment. Depending on what firmware i upload they often fail. Here is the riot os hello world example.  I have tested all firmware i have on a local device where it works fine. 

![image](https://github.com/iot-lab/iot-lab/assets/8879988/a46a59c9-3ec9-436d-96c2-42f6d49701e6)

This might be a space issue as i sometimes get the following log output in the `.iot-lab/last/log` folder

![image](https://github.com/iot-lab/iot-lab/assets/8879988/00a9c8b1-5c90-44ad-ab52-9825fd1f9c98)

**Comment by schrein** [comment]
Should be fixed now, I closed the issue
