### ISSUE TITLE
 Issue Finding Mobile Node IDs on IoT-LAB

### ISSUE THREAD

**Issue by HADJMOHAND** [iot-lab/iot-lab#317]
Hello,

I am experiencing difficulties in identifying mobile nodes on the IoT-LAB platform. Specifically, I am unable to find the IDs of the mobile nodes at the Grenoble site.

Here are some additional details:

I want to submit an experiment using mobile nodes, but I am having trouble obtaining the list of nodes that support mobility.
I have tried using the iotlab-node and iotlab-experiment commands, but I have not been successful in identifying the mobile nodes.
Do you have any recommendations or specific steps to follow to find the IDs of mobile nodes? Perhaps there is a documentation or guide that I have not yet consulted?

Thank you in advance for your assistance.

**Comment by schrein** [comment]
Hello, the support of the mobile nodes in IoT-LAB is currently disable in the actual testbed. Best regards.
