### ISSUE TITLE
Issue on a8 nodes booking in Strasbourg

### ISSUE THREAD

**Issue by guillaumerosinosky** [iot-lab/iot-lab#319]
Hello,

I don't manage to book a8 nodes in the Strasbourg datacenter, with EnosLib or with the UI. It's working well in Saclay and Grenoble.
Thanks a lot!

![image](https://github.com/user-attachments/assets/96f270e4-392d-4c81-a4e6-89f926f2c5a9)

**Comment by schrein** [comment]
Hello Guillaume, it's fix now. It should be working again. Sorry for the inconvenience.
