### ISSUE TITLE
Tweak IPV6 on contiki to enable compression

### ISSUE THREAD

**Issue by fambon** [iot-lab/iot-lab#47]
- [ ] investigate sicslowpan requirements (addresses, configuration settings, code mods) 
- [ ] decide addressing scheme (logical, using flash-stored info, or physical, using uuid)
- [ ] update contiki platforms init code
- [ ] update idle-firmware (if using flash-stored addressing scheme)
- [ ] provide documentation and example

**Comment by fsaintma** [comment]
new port Contiki version 3.0
