### ISSUE TITLE
M3 example application with tiles and step detection 

### ISSUE THREAD

**Issue by pissard** [iot-lab/iot-lab#53]
Using the M3 nodes located under the tiles in Grenoble corridors, the application on each M3 node consists of detecting human step on their tile with the accelerometer signal. The algorithm principle is to detect peaks as for a classical pedometer. The result of detection can be communicated using serial link or to a sink node using a wireless network.

**Comment by cladmi** [comment]
https://github.com/iot-lab/iot-lab/wiki/Running-the-Smart-Tiles-Demo
