### ISSUE TITLE
install M3 OML plot script on frontend server for users

### ISSUE THREAD

**Issue by pissard** [iot-lab/iot-lab#54]
iot-lab/tools_and_scripts/plot_oml_consum.py 
iot-lab/tools_and_scripts/plot_oml_radio.py

**Comment by teaserrahul** [comment]
I added a new experiment with tutorial_m3.elf firmware and radio monitoring profile as shown in [https://www.iot-lab.info/tutorials/monitoring-radio-m3/]

But there are no oml files are generating at the destined folder (please see the attached screenshot)

![screenshot 2018-10-14 21 31 16](https://user-images.githubusercontent.com/26592576/46919158-d0663b80-cff8-11e8-8131-8662f35bba23.png)
![screenshot 2018-10-14 21 31 45](https://user-images.githubusercontent.com/26592576/46919159-d0663b80-cff8-11e8-9976-26841ea43539.png)
