### ISSUE TITLE
update header files

### ISSUE THREAD

**Issue by pissard** [iot-lab/iot-lab#55]
You must update and harmonize the header file on iotlab, wsn430, openlab, contrib. contiki
- change the licence of wsn430 (mail to authors) -> lgpl
- openlab....

When all is fixed = APP.

**Comment by cladmi** [comment]
Done for cli-tools and aggregation-tools.

**Comment by vandaele** [comment]
Done in 2015, and APP for iot-lab-gateway, aggregation-tools, robots and cli-tools.
New deposit in 2019 for core software.
