### ISSUE TITLE
Remove nodes with too many fail deployements from the bookable nodes.

### ISSUE THREAD

**Issue by cladmi** [iot-lab/iot-lab#64]
I launched around 10 experiments in parallel with automated selection of two nodes cc1101 in Grenoble and I only got 2 experiments where I got the two nodes that where successfully deployed. 

Experiments from 7159 to 7169:
- Both successfully deployed: 7167 and 7169
- Both with failed deployment: 7162 and 7165

I think the nodes should be removed from bookable nodes after too many deployment errors.

**Comment by schrein** [comment]
EOL nodes
