### ISSUE TITLE
Never Deads Do Die

### ISSUE THREAD

**Issue by fambon** [iot-lab/iot-lab#94]
Phase one of M3 nodes deployment unrolled with a set of "robust" nodes, which did not exhibit FTDI bug #13.  Selected nodes have undergone a number of experiments without issues and thus qualified, however, this does not mean they will never fail.  This issue originally tracked which of the elected grenoble m3 nodes had failed to deploy.  

As of 2014-10-15, all nodes have been patched with a new u-boot which cures most of the cases.  Some nodes however still exhibit issues, such as no open-node, no control-node, or simply fail to boot.

This issue now tracks globally which nodes have issues, M3 or A8, on any site.

**Comment by cladmi** [comment]
Not related anymore to original problem with usb issues.
